'use client';
import { useState } from 'react';
import Link from 'next/link';
import { House, Layers3, Activity, Calculator, MessagesSquare, ArrowUpRight, ArrowRight, ShieldCheck, CircleHelp, Wallet, Building2, Landmark, ChevronRight, Check, CircleAlert } from 'lucide-react';
import { Sidebar, SidebarProvider } from '@/components/ui/sidebar';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
const names = ['家庭财务首页','家庭资产全景','家庭财务体检','提前还贷情景模拟','财务解释助手'];
const paths = ['/','/assets','/checkup','/simulation','/assistant'];
const icons = [House, Layers3, Activity, Calculator, MessagesSquare];
const intros = ['把分散的资产负债，放回同一个家庭视角。','从账户与资料，到一张完整的家庭资产负债表。','四个指标，读懂家庭财务中值得关注的地方。','利息少一些，现金也少一些。把两种选择放在一起看。','让数字更容易理解，让选择有更清楚的依据。'];
const checks = [
  {name:'应急资金月数',value:'5.0',unit:'个月',state:'较稳健',formula:'10 ÷ 2.0 = 5.0 个月',copy:'现有可立即使用资金，可覆盖约 5 个月必要支出。',width:50,good:true,detail:'应急资金 10 万元 · 月度必要支出 2.0 万元'},
  {name:'负债水平',value:'42.2',unit:'%',state:'需关注',formula:'121 ÷ 287 = 42.2%',copy:'每 100 万元资产，对应约 42.2 万元负债。',width:42.2,detail:'总负债 121 万元 · 总资产 287 万元'},
  {name:'流动资产比例',value:'20.6',unit:'%',state:'需关注',formula:'59 ÷ 287 = 20.6%',copy:'约五分之一资产为现金、存款、理财和基金，实际取用速度不同。',width:20.6,detail:'流动资产 59 万元 · 总资产 287 万元'},
  {name:'资产集中度',value:'76.7',unit:'%',state:'较高',formula:'220 ÷ 287 = 76.7%',copy:'家庭资产主要集中在住房，房产价值不等于可用现金。',width:76.7,detail:'家庭住房 220 万元 · 总资产 287 万元'},
];
const answers = [
  {question:'为什么应急资金要关注？',title:'有资产，也需要随时可用的现金。',text:'王先生家庭可立即使用的应急资金为 10 万元，月度必要支出为 2.0 万元，因此可以覆盖 5.0 个月。如果将这 10 万元全部用于提前还贷，当前口径下的应急资金会降至 0。',note:'收入稳定性、未来大额支出、其他资金的实际取用时间。',formula:'10 万元 ÷ 2.0 万元/月 = 5.0 个月'},
  {question:'为什么房产占比高？',title:'房产占了大部分资产，但不能随时用于支出。',text:'家庭住房为 220 万元，总资产为 287 万元，房产占比为 76.7%。这反映出家庭资产集中于住房；房产价格变化对总资产影响较大，出售或变现通常也需要时间。',note:'自住需求、房屋价值变化、变现时间，以及家庭其他可用资金。',formula:'220 万元 ÷ 287 万元 = 76.7%'},
  {question:'家庭负债怎么看？',title:'负债比例只是一个视角，还要看偿付压力。',text:'房贷余额 118 万元，加上信用卡本期应还 3 万元，总负债为 121 万元。与总资产 287 万元相比，负债水平为 42.2%。这一比例不能单独判断家庭是否有还款压力。',note:'收入与月供的关系、信用卡到期安排、利率和收入稳定性。',formula:'(118 + 3) 万元 ÷ 287 万元 = 42.2%'},
  {question:'提前还贷一定更好吗？',title:'利息成本与资金灵活性，需要同时比较。',text:'按本演示的固定结果，提前还款 10 万元、保持期限不变，月供约从 6603 元降至 6044 元，累计利息差约 3.43 万元。但可立即使用资金也从 10 万元降至 0，应急覆盖从 5.0 个月降至 0。',note:'手续费及违约金、银行实际计息与办理规则、收入稳定性及近期资金需求。这里不替家庭作决定。',formula:'月供约减少 559 元 · 可立即使用资金减少 10 万元'},
];
function Action({page,children,primary=false}:{page:number;children:React.ReactNode;primary?:boolean}) { return <Link className={primary?'button primary':'button'} href={paths[page]}>{children}<ArrowRight size={16}/></Link>; }
function Tag({children,good=false}:{children:React.ReactNode;good?:boolean}) {return <span className={`tag ${good?'good':''}`}>{children}</span>;}
function Overview() {return <>
  <div className="summary-grid"><div className="metric"><span>总资产 <Layers3 size={18}/></span><div className="number">287<small>万元</small></div><p>家庭所有资产的合计</p></div><div className="metric"><span>总负债 <Landmark size={18}/></span><div className="number">121<small>万元</small></div><p>住房贷款与信用卡本期应还</p></div><div className="metric net"><span>净资产 <ShieldCheck size={18}/></span><div className="number">166<small>万元</small></div><p>总资产 287 − 总负债 121</p></div></div>
  <div className="overview-grid"><section className="panel structure"><div className="section-head"><h2>家庭资产结构</h2><span className="muted">总资产口径</span></div><div className="structure-body"><div className="donut" role="img" aria-label="房产76.7%，金融资产21.6%，保险现金价值1.7%"><div><span>资产总额</span><strong>287<small>万元</small></strong></div></div><div className="legend">{[['房产','220','76.7%'],['金融资产','62','21.6%'],['保险现金价值','5','1.7%']].map((x,i)=><div className="legend-row" key={x[0]}><span className={`dot dot-${i}`}/><div><b>{x[0]}</b><span>{x[2]}</span></div><strong>{x[1]}<small>万元</small></strong></div>)}</div></div><div className="panel-note">金融资产包含现金/存款、银行理财、基金及养老金账户。</div><Link href="/assets" className="text-link">查看资产全景 <ArrowUpRight size={16}/></Link></section>
  <section className="panel attention"><div className="section-head"><h2>值得关注</h2><span className="tiny-label">财务快照</span></div><div className="attention-row"><div className="icon-box green"><Wallet size={20}/></div><div><div className="row-title">应急资金 <Tag good>较稳健</Tag></div><p>可覆盖约 <strong>5.0 个月</strong>必要支出</p></div></div><div className="attention-row"><div className="icon-box amber"><Building2 size={20}/></div><div><div className="row-title">房产占比 <Tag>较高</Tag></div><p>占总资产 <strong>76.7%</strong>，需关注集中度</p></div></div><div className="attention-bottom"><span>从看清家底，到理解指标</span><Action page={2} primary>进入财务体检</Action></div></section></div>
  <section className="scenario-banner"><div className="icon-box"><Calculator size={24}/></div><div><h2>提前还 10 万元，家庭财务会怎样？</h2><p>同时比较月供、利息与手里的可用资金。</p></div><Action page={3}>开始情景测算</Action></section>
</>;}
const assetRows = [ ['现金/存款','现金及备用金 2 · 工行工资卡 8 · 建行家庭存款 12','现金 / 工行 / 建行',22],['银行理财','银行理财产品','银行',22],['基金','支付宝基金','支付宝',15],['房产','家庭住房','房产资料',220],['保险现金价值','保单现金价值','保单资料',5],['养老金账户','养老金账户余额','养老金账户',3] ];
function Assets(){return <><div className="compact-summary"><span>总资产 <b>287 <small>万元</small></b></span><span>总负债 <b>121 <small>万元</small></b></span><span>净资产 <b>166 <small>万元</small></b></span></div><section className="panel assets-panel"><div className="section-head"><h2>资产明细</h2><span className="muted">家庭共同视角 · 金额单位：万元</span></div><Table><TableHeader><TableRow><TableHead>资产类别</TableHead><TableHead>组成 / 资料</TableHead><TableHead>机构来源</TableHead><TableHead className="align-right">金额</TableHead></TableRow></TableHeader><TableBody>{assetRows.map((r,i)=><TableRow key={String(r[0])}><TableCell><span className="asset-name"><span className={`asset-dot asset-${i}`}/>{r[0]}</span></TableCell><TableCell className="muted">{r[1]}</TableCell><TableCell><span className="source-tag">{r[2]}</span></TableCell><TableCell className="align-right amount">{r[3]}</TableCell></TableRow>)}</TableBody></Table><div className="table-total">资产合计 <b>287 <small>万元</small></b></div></section><div className="liabilities"><div><Landmark size={22}/><h2>负债单列</h2></div><span>住房贷款余额 <b>118 <small>万元</small></b></span><span>信用卡本期应还 <b>3 <small>万元</small></b></span><span className="debt-total">合计 <b>121 <small>万元</small></b></span></div><div className="bottom-actions"><p>上述来源仅用于说明信息归属，均为手工整理的模拟数据。</p><Action page={2} primary>查看体检</Action></div></>;}
function Checkup(){return <><div className="insight-strip"><Activity size={22}/><p>应急资金约可覆盖 <b>5.0 个月</b>支出，资产主要集中在<b>家庭住房</b>。</p></div><div className="check-grid">{checks.map((c,i)=><section className="panel check-card" key={c.name}><div className="section-head"><h2><span className="index">0{i+1}</span>{c.name}</h2><Tag good={c.good}>{c.state}</Tag></div><div className="check-value">{c.value}<small>{c.unit}</small></div><div className={`meter ${c.good?'positive':''}`}><span style={{width:`${c.width}%`}}/></div><p>{c.copy}</p><div className="formula">{c.formula}<span>{c.detail}</span></div></section>)}</div><div className="bottom-actions"><p>状态为模拟案例的提示性描述；流动资产不等于可立即使用的应急资金。</p><div className="actions"><Action page={4}>为什么要关注</Action><Action page={3} primary>测算提前还贷</Action></div></div></>;}
function Simulation(){return <><div className="parameters"><span><small>剩余本金</small><b>118 万元</b></span><span><small>年利率</small><b>3.1%</b></span><span><small>剩余期限</small><b>20 年</b></span><span><small>还款方式</small><b>等额本息</b></span><span><small>比较前提</small><b>期限不变</b></span></div><div className="compare-grid">{[true,false].map(a=><section className={`panel comparison ${a?'plan-a':'plan-b'}`} key={String(a)}><div className="plan-heading"><span className="plan-letter">{a?'A':'B'}</span><div><h2>{a?'提前还 10 万元':'保留 10 万元现金'}</h2><p>{a?'降低贷款本金与后续月供':'维持原贷款，保留资金灵活性'}</p></div></div><div className="monthly"><span>预计月供</span><strong>{a?'6044':'6603'}<small>元 / 月</small></strong><span>{a?'较原月供约减少 559 元':'与原月供保持一致'}</span></div><div className="compare-row"><span>剩余本金</span><b>{a?'108':'118'} <small>万元</small></b></div><div className="compare-row"><span>累计利息差</span><b>{a?'约少 3.43':'基准方案'}{a&&<small> 万元</small>}</b></div><div className="liquidity-box"><div className="compare-row"><span>可立即使用资金</span><b>{a?'0':'10'} <small>万元</small></b></div><div className="compare-row"><span>应急资金覆盖</span><b>{a?'0':'5.0'} <small>个月</small></b></div><p>{a?'现有应急资金全部用于提前还款':'保留约 5 个月必要支出的缓冲'}</p></div></section>)}</div><div className="tradeoff"><CircleAlert size={21}/><p><b>同一个选择，两方面影响。</b>提前还贷减少利息成本，同时降低家庭流动性。</p></div><div className="bottom-actions"><p>不考虑手续费及违约金；结果仅为模拟比较，不构成贷款或投资建议。<br/>数值为任务书固定演示值，实际结果以银行计算和办理规则为准。</p><div className="actions"><Action page={2}>返回体检</Action><Action page={4} primary>查看解释</Action></div></div></>;}
function Assistant(){const [active,setActive]=useState(0);const a=answers[active];return <><div className="assistant-grid"><section className="panel questions"><div className="section-head"><h2>从一个问题开始</h2></div><p className="muted">关于王先生家庭，你想了解什么？</p><div className="question-list">{answers.map((x,i)=><button key={x.question} onClick={()=>setActive(i)} aria-pressed={active===i} className={active===i?'selected':''}><CircleHelp size={18}/><span>{x.question}</span><ChevronRight size={16}/></button>)}</div><div className="preset-note"><ShieldCheck size={18}/><span>仅解释本案例的数据与计算逻辑</span></div></section><section className="panel answer" aria-live="polite" aria-atomic="true"><div className="answer-label"><span className="icon-box"><MessagesSquare size={22}/></span><div><b>家底 · 财务解释</b><span>预设回答</span></div></div><h2>{a.title}</h2><p>{a.text}</p><div className="answer-formula">{a.formula}</div><div className="consider"><b>还要放在一起考虑</b><p>{a.note}</p></div><div className="answer-source"><Check size={15}/>依据：王先生家庭模拟数据</div></section></div><div className="bottom-actions"><p>预设解释，不连接真实 AI；不构成投资、贷款或保险建议。</p><div className="actions"><Action page={2}>返回体检</Action><Action page={3} primary>情景测算</Action></div></div></>;}
export default function Dashboard({page}:{page:number}){const View=[Overview,Assets,Checkup,Simulation,Assistant][page];return <SidebarProvider><a className="skip-link" href="#main">跳到主要内容</a><Sidebar collapsible="none" className="app-sidebar"><Link href="/" className="brand"><span className="brand-icon"><House size={25}/></span><span>家底<small>家庭财务，看得清</small></span></Link><div className="nav-caption">家庭财务工作台</div><nav aria-label="主要导航">{names.map((name,i)=>{const Icon=icons[i];return <Link href={paths[i]} key={name} className={`nav-item ${page===i?'active':''}`} aria-current={page===i?'page':undefined}><Icon size={19}/><span>{name}</span>{page===i&&<span className="nav-active-dot"/>}</Link>;})}</nav><div className="sidebar-bottom"><div className="family-avatar">王</div><div><b>王先生家庭</b><span>模拟家庭档案</span></div></div></Sidebar><div className="workspace"><header className="topbar"><div className="breadcrumb">家庭工作台<ChevronRight size={14}/><span>{names[page]}</span></div><span className="demo-badge"><span/>模拟数据 / 原型演示</span></header><main id="main"><div className="page-heading"><div><div className="eyebrow">JIADI · FAMILY FINANCE</div><h1>{names[page]}</h1><p>{intros[page]}</p></div><div className="update">王先生家庭<span>数据更新时间 2026.09.24</span></div></div><View/><footer className="footer"><span><ShieldCheck size={14}/>数据仅用于原型演示，未连接银行、OCR 或真实 AI。</span><Link href="/">返回首页 <ArrowUpRight size={13}/></Link><span className="page-count">0{page+1} / 05</span></footer></main></div></SidebarProvider>;}
